version: 2.1
orbs:
  node: circleci/node@5.1.0
  python: circleci/python@2.1.1
jobs:
  ts-check:
    executor:
      name: node/default
      tag: "24.7"
    steps:
      - checkout
      - node/install-packages:
          app-dir: "type-generation"
      - run: |
          npm run -C type-generation check
  js-unit:
    executor:
      name: node/default
      tag: "24.7"
    steps:
      - checkout
      - node/install-packages:
          app-dir: "input-projects/browser-dom"
      - node/install-packages:
          app-dir: "type-generation"
      - run: |
          npm run -C type-generation test
  generate:
    executor:
      name: node/default
      tag: "24.7"
    steps:
      - checkout
      - node/install-packages:
          app-dir: "input-projects/browser-dom"
      - node/install-packages:
          app-dir: "input-projects/cloudflare-workers"
      - node/install-packages:
          app-dir: "type-generation"
      - run: |
          ./generate_tests.sh
      - persist_to_workspace:
          root: .
          paths:
            - ./generated
  test:
    executor:
      name: python/default
      tag: "3.13"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            cd mypy-tests
            mkdir test-results
            uv run pytest --junitxml=test-results/junit.xml --verbose --color=yes
      - store_test_results:
          path: mypy-tests/test-results
workflows:
  build_and_test:
    jobs:
      - ts-check
      - js-unit
      - generate
      - test:
          requires:
            - generate
